#!/bin/bash -e

other_branch=$1

repo_root=$(git rev-parse --show-toplevel)
current_branch=$(git rev-parse --abbrev-ref HEAD)

if ! echo $current_branch | egrep -q "^$USER/"
then
    echo "you aren't on a '$USER/' branch"
    exit 1
fi

git fetch

if [ -z "$other_branch" ]
then
    echo
    echo Usage: $0 other_branch
    echo
    echo "Related branches and their diffs (if any):"
    echo

    twig=$(basename $current_branch)
    for b in $(git branch -a | tr '*' ' ' | egrep "/$twig$" | egrep -v "^$current_branch$")
    do 
        ahead=$(git diff --shortstat ...${b})
        behind=$(git diff --shortstat ${b}...)
        if [ -n "$ahead" ]
        then
            printf "%40s is ahead:\n" $b 
            git diff --stat ...${b} 
        fi
        if [ -n "$behind" ]
        then
            printf "%40s is behind: %s\n" $b "$behind"
        fi

        # also see https://git.seveas.net/previewing-a-merge-result.html for a
        # different approach with more detailed diffs:
        # git merge-tree $(git merge-base HEAD develop) HEAD develop
    done

    exit 1
fi

msg=/tmp/mob-consensus.msg

printf "mob-consensus merge from $other_branch onto $current_branch\n\n" > $msg
# printf "\n\n" > $msg

set -x
git log ..$other_branch --pretty=format:"Co-authored-by: %an <%ae>" \
    | grep -v $(git config --get user.email) \
    | sort -u >> $msg

if [ -n "$(git status --porcelain)" ]
then 
    set +x
    echo you have uncommitted changes
    exit 1
fi

if ! git merge --no-commit --no-ff $other_branch
then
    # deal with merge conflicts
    git mergetool -t vimdiff 
fi

# commit during merge will ignore `-t`, so we replace the
# default commit message here as well
# XXX might instead want to use -m or -F flag on the above merge 
cp $msg $repo_root/.git/MERGE_MSG

# review all changes
git difftool -t vimdiff HEAD

if ! git commit -e -F $msg
then
    set +x
    echo "don't forget to push"
    exit 1
fi

git push

