#!/bin/bash -e

other_branch=$1

if [ -z "$other_branch" ]
then
    echo usage: $0 other_branch
    exit 1
fi

current_branch=$(git rev-parse --abbrev-ref HEAD)

msg=/tmp/mob-consensus.msg

# printf "mob-consensus merge from $other_branch onto $current_branch\n\n" > $msg
printf "\n\n" > $msg

git log ..$other_branch --pretty=format:"Co-authored-by: %an <%ae>" \
    | grep -v $(git config --get user.email) \
    | sort -u >> $msg

if [ -n "$(git status --porcelain)" ]
then 
  echo you have uncommitted changes
  exit 1
fi

set -x
if ! git merge --no-commit --no-ff $other_branch
then
    git mergetool -t vimdiff 
fi
git difftool -t vimdiff HEAD

# XXX not working while a merge is in progress...
# git commit -t $msg
# git push

# ...so let's do this manually for now:
echo include this file in your commit message: $msg

